### ISSUE TITLE
Vendor data present in the RubyGems releases

### ISSUE THREAD

**Issue by mensfeld** [ory/kratos-client-ruby#1]
Hey there,

My name is Maciej Mensfeld and I run security & quality assessment for OSS libraries using WhiteSource https://Diffend.io.

While reviewing the changes for this lib, I noticed, that the vendor directory is being included.

Is this needed? Usually, it's added by mistake and causes:

a) confusion
b) problems when tracking changes
c) extensive library size

In this particular case this library used to be 137KB big and now it's over 63 times bigger

ref: https://my.diffend.io/gems/ory-kratos-client/0.7.3.alpha8/0.7.5.alpha2

If the presence of vendor data is valid I would love the reasoning. Thanks!

**Comment by aeneasr** [comment]
Hello, the library is auto-generated using openapi-generator, which probably has this issue and/or reasoning for it!

**Comment by mensfeld** [comment]
@aeneasr it was not like this for previous releases (not including last 2), thus my gut feeling is, something have changed here.

**Comment by aeneasr** [comment]
That is coming from openapi-generator as that file is autogenerated. If it is solved there (PRs get merged quickly there of they are small and helpful) it will be solved here as well!

Looking at git blame it appears that this was always there. Also, this repo more like a mirror (we introduced it a few weeks back) as the build happens over at ory/sdk.

What trouble is this causing? Unfortunately I have never worked with Ruby :/

**Comment by mensfeld** [comment]
@aeneasr thank you for the explanation.

> What trouble is this causing? 

1. Extensive lib size (note, RubyGems is non profit and while 8MB may not seem a lot, when downloaded 100 000 times, it's already 781GB).
2. Security risk - it is much, much, much harder to actually track changes in between releases when there is more than 2600 files of noise.

**Comment by aeneasr** [comment]
On the second I have a different opinion (probably because Go used to do it that way) because vendored files are less likely to be part of a supply chain attack (see event-stream hack on NPM) as every change is vetted in a PR review. However, since these clients here are autogenerated and it appears to be best practice to not bundle dependencies in Ruby, I agree with your conclusion! Also, in the real world, it’s just so much more convenient to not pull hundreds of megabytes of code from a single git remote :)

The relevant pieces of code are:

https://github.com/ory/sdk/blob/30d18263aa40b7c6adae078611a7c19a1eb2fb00/scripts/generate.sh#L162

https://github.com/ory/sdk/blob/30d18263aa40b7c6adae078611a7c19a1eb2fb00/scripts/test.sh#L37

https://github.com/ory/sdk/blob/30d18263aa40b7c6adae078611a7c19a1eb2fb00/scripts/release.sh#L138

I believe the regression was introduced as I added the new test pipeline which is pulling dependencies to execute tests, and then is bundling them, and then releasing:

https://github.com/ory/sdk/blob/30d18263aa40b7c6adae078611a7c19a1eb2fb00/.circleci/config.yml#L16

There are two ways to fix that:

1. Delete the vendor folder before bundling & releasing it
2. Update openapi-generator template so that it does not bundle vendor data

The second would be preferable as I think it is a problem in the generator. The first option is a workaround.

Would be awesome if you could contribute either one or both :)

**Comment by mensfeld** [comment]
> On the second I have a different opinion (probably because Go used to do it that way) because vendored files are less likely to be part of a supply chain attack (see event-stream hack on NPM) as every change is vetted in a PR review.

Depends who and how attacks. Vendor data (that is anyhow not used when distributed the way it is in this case) can be explicitly required in the gem code. What that means, is, that potentially you could hide malicious code within all of this "noise" that comes with it.

event-stream is just a tip of the iceberg. For the past year there were more than 60 malicious packages that I detected and removed (I'm part of RubyGems sec team). Not having to analyze (whether with tools or manually) diffs of that size makes my life easier and when it comes with benefits to the packages owners like you, I open issues for mutual gains :)

> Also, in the real world, it’s just so much more convenient to not pull hundreds of megabytes of code from a single git remote :)

Absolutely!

> Would be awesome if you could contribute either one or both :)

I will look into that at the end of this week.

**Comment by aeneasr** [comment]
I see - that makes sense! I am probably a bit biased from the old days of Go where vendoring deps was considered best practice both for getting reproducible builds and for preventing event-stream type of attacks. But they also changed course and we now have go.mod!

As you probably have tons of work on your hand, I am also happy to take a look once I am back from my vacation next week :)

Also thank you for keeping the Ruby ecosystem secure!

**Comment by mensfeld** [comment]
> I see - that makes sense! I am probably a bit biased from the old days of Go where vendoring deps was considered best practice both for getting reproducible builds and for preventing event-stream type of attacks.

Yup and it still would be but would create a lot of issues, especially for languages like Ruby, where you cannot (in contrary to JS) run several versions of the same package in one runtime.
